FROM php:8.4-fpm

# Install dependensi sistem untuk Laravel (GD, MySQL, Zip)
RUN apt-get update && apt-get install -y \
    libpng-dev libjpeg-dev libfreetype6-dev zip libzip-dev unzip git \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo_mysql gd zip

# Ambil Composer terbaru untuk instalasi Laravel 12
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

#  Install Node.js (via NodeSource)
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs

WORKDIR /var/www/html